global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['34.205.93.45:8081']  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']