- name: Deploy Grafana and Prometheus
  hosts: ec2_instances
  become: yes
  vars:
    ec2_public_ip: "34.205.93.45"  
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose dependencies
      yum:
        name:
          - curl
          - python3
        state: present

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Verify Docker Compose installation
      command: /usr/local/bin/docker-compose --version
      register: docker_compose_version
      failed_when: "'docker-compose' not in docker_compose_version.stdout"

    - name: Create directory for Grafana and Prometheus
      file:
        path: ~/CounterApp/ansible
        state: directory

    - name: Create Docker network if it doesn't exist
      command: docker network create monitoring_network
      ignore_errors: yes  # Ignore errors if the network already exists

    - name: Create docker-compose.yml
      copy:
        dest: ~/CounterApp/ansible/docker-compose.yml
        content: |
          version: '3'
          services:
            prometheus:
              image: prom/prometheus:latest
              container_name: prometheus
              volumes:
                - ./prometheus.yml:/etc/prometheus/prometheus.yml
              ports:
                - "9090:9090"
              networks:
                - monitoring_network

            grafana:
              image: grafana/grafana:latest
              container_name: grafana
              ports:
                - "3000:3000"
              depends_on:
                - prometheus
              networks:
                - monitoring_network

          networks:
            monitoring_network:
              external: true

    - name: Create prometheus.yml
      copy:
        dest: ~/CounterApp/ansible/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'flask_app'
              static_configs:
                - targets: ['flask_api_app:8081']
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Deploy Grafana and Prometheus with Docker Compose
      command:
        cmd: /usr/local/bin/docker-compose up -d
        chdir: ~/CounterApp/ansible
        executable: /bin/bash
